services:
  - type: web
    name: lpg-stock-dashboard
    env: python
    plan: free
    buildCommand: pip install -r "LGP web dashbord/requirements.txt"
    startCommand: gunicorn --chdir "LGP web dashbord" app:server
    autoDeploy: true
